services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
      - ai-service

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  ai-service:
    build:
      context: ./ai-service
    container_name: ai-service
    ports:
      - "8001:8001"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend

volumes:
  mongo-data:
